name: Support Question
description: Get help with installation or configuration
title: "[Support] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Need help getting CodGuard working? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: What do you need help with?
      description: Describe your question or issue
      placeholder: "I'm not sure how to configure the API key..."
    validations:
      required: true

  - type: input
    id: opencart-version
    attributes:
      label: OpenCart Version
      placeholder: "4.0.2.3"
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: CodGuard Extension Version
      placeholder: "2.9.0"
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: What steps have you already taken?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots of your configuration or the issue
      placeholder: Drag and drop images here
    validations:
      required: false
